/**
 * Comprehensive database of German cities for lead generation.
 *
 * Contains ~380 cities across all 16 Bundesländer, with coordinates
 * and utility functions for radius search and state filtering.
 */

export interface City {
  name: string;
  state: string;
  lat: number;
  lng: number;
}

/** All 16 German Bundesländer */
export const ALL_STATES: string[] = [
  'Schleswig-Holstein',
  'Hamburg',
  'Niedersachsen',
  'Bremen',
  'Nordrhein-Westfalen',
  'Hessen',
  'Rheinland-Pfalz',
  'Baden-Württemberg',
  'Bayern',
  'Saarland',
  'Berlin',
  'Brandenburg',
  'Mecklenburg-Vorpommern',
  'Sachsen',
  'Sachsen-Anhalt',
  'Thüringen',
];

export const GERMAN_CITIES: City[] = [
  // ─── Berlin ───────────────────────────────────────────────────────────
  { name: 'Berlin', state: 'Berlin', lat: 52.52, lng: 13.41 },

  // ─── Hamburg ──────────────────────────────────────────────────────────
  { name: 'Hamburg', state: 'Hamburg', lat: 53.55, lng: 9.99 },

  // ─── Bremen ───────────────────────────────────────────────────────────
  { name: 'Bremen', state: 'Bremen', lat: 53.08, lng: 8.80 },
  { name: 'Bremerhaven', state: 'Bremen', lat: 53.54, lng: 8.58 },

  // ─── Schleswig-Holstein ───────────────────────────────────────────────
  { name: 'Kiel', state: 'Schleswig-Holstein', lat: 54.32, lng: 10.14 },
  { name: 'Lübeck', state: 'Schleswig-Holstein', lat: 53.87, lng: 10.69 },
  { name: 'Flensburg', state: 'Schleswig-Holstein', lat: 54.79, lng: 9.44 },
  { name: 'Neumünster', state: 'Schleswig-Holstein', lat: 54.07, lng: 9.98 },
  { name: 'Norderstedt', state: 'Schleswig-Holstein', lat: 53.70, lng: 9.99 },
  { name: 'Elmshorn', state: 'Schleswig-Holstein', lat: 53.75, lng: 9.65 },
  { name: 'Pinneberg', state: 'Schleswig-Holstein', lat: 53.66, lng: 9.80 },
  { name: 'Wedel', state: 'Schleswig-Holstein', lat: 53.58, lng: 9.70 },
  { name: 'Ahrensburg', state: 'Schleswig-Holstein', lat: 53.67, lng: 10.24 },
  { name: 'Itzehoe', state: 'Schleswig-Holstein', lat: 53.93, lng: 9.52 },
  { name: 'Rendsburg', state: 'Schleswig-Holstein', lat: 54.30, lng: 9.66 },
  { name: 'Bad Oldesloe', state: 'Schleswig-Holstein', lat: 53.81, lng: 10.38 },
  { name: 'Henstedt-Ulzburg', state: 'Schleswig-Holstein', lat: 53.79, lng: 9.98 },
  { name: 'Geesthacht', state: 'Schleswig-Holstein', lat: 53.44, lng: 10.37 },
  { name: 'Reinbek', state: 'Schleswig-Holstein', lat: 53.51, lng: 10.25 },
  { name: 'Bad Segeberg', state: 'Schleswig-Holstein', lat: 53.94, lng: 10.31 },
  { name: 'Husum', state: 'Schleswig-Holstein', lat: 54.49, lng: 9.05 },

  // ─── Niedersachsen ────────────────────────────────────────────────────
  { name: 'Hannover', state: 'Niedersachsen', lat: 52.37, lng: 9.74 },
  { name: 'Braunschweig', state: 'Niedersachsen', lat: 52.27, lng: 10.52 },
  { name: 'Oldenburg', state: 'Niedersachsen', lat: 53.14, lng: 8.21 },
  { name: 'Osnabrück', state: 'Niedersachsen', lat: 52.28, lng: 8.04 },
  { name: 'Wolfsburg', state: 'Niedersachsen', lat: 52.42, lng: 10.79 },
  { name: 'Göttingen', state: 'Niedersachsen', lat: 51.53, lng: 9.94 },
  { name: 'Salzgitter', state: 'Niedersachsen', lat: 52.15, lng: 10.33 },
  { name: 'Hildesheim', state: 'Niedersachsen', lat: 52.15, lng: 9.95 },
  { name: 'Delmenhorst', state: 'Niedersachsen', lat: 53.05, lng: 8.63 },
  { name: 'Wilhelmshaven', state: 'Niedersachsen', lat: 53.53, lng: 8.11 },
  { name: 'Lüneburg', state: 'Niedersachsen', lat: 53.25, lng: 10.41 },
  { name: 'Celle', state: 'Niedersachsen', lat: 52.62, lng: 10.08 },
  { name: 'Garbsen', state: 'Niedersachsen', lat: 52.42, lng: 9.60 },
  { name: 'Hameln', state: 'Niedersachsen', lat: 52.10, lng: 9.36 },
  { name: 'Lingen', state: 'Niedersachsen', lat: 52.52, lng: 7.32 },
  { name: 'Langenhagen', state: 'Niedersachsen', lat: 52.44, lng: 9.74 },
  { name: 'Nordhorn', state: 'Niedersachsen', lat: 52.43, lng: 7.07 },
  { name: 'Wolfenbüttel', state: 'Niedersachsen', lat: 52.16, lng: 10.54 },
  { name: 'Goslar', state: 'Niedersachsen', lat: 51.91, lng: 10.43 },
  { name: 'Peine', state: 'Niedersachsen', lat: 52.32, lng: 10.24 },
  { name: 'Emden', state: 'Niedersachsen', lat: 53.37, lng: 7.21 },
  { name: 'Cuxhaven', state: 'Niedersachsen', lat: 53.87, lng: 8.69 },
  { name: 'Stade', state: 'Niedersachsen', lat: 53.60, lng: 9.48 },
  { name: 'Melle', state: 'Niedersachsen', lat: 52.20, lng: 8.34 },
  { name: 'Neustadt am Rübenberge', state: 'Niedersachsen', lat: 52.50, lng: 9.46 },
  { name: 'Laatzen', state: 'Niedersachsen', lat: 52.32, lng: 9.80 },
  { name: 'Buchholz in der Nordheide', state: 'Niedersachsen', lat: 53.33, lng: 9.87 },
  { name: 'Leer', state: 'Niedersachsen', lat: 53.23, lng: 7.45 },
  { name: 'Aurich', state: 'Niedersachsen', lat: 53.47, lng: 7.48 },
  { name: 'Wunstorf', state: 'Niedersachsen', lat: 52.43, lng: 9.43 },
  { name: 'Seelze', state: 'Niedersachsen', lat: 52.39, lng: 9.60 },
  { name: 'Gifhorn', state: 'Niedersachsen', lat: 52.49, lng: 10.55 },
  { name: 'Cloppenburg', state: 'Niedersachsen', lat: 52.85, lng: 8.04 },
  { name: 'Meppen', state: 'Niedersachsen', lat: 52.69, lng: 7.29 },
  { name: 'Helmstedt', state: 'Niedersachsen', lat: 52.23, lng: 11.01 },
  { name: 'Uelzen', state: 'Niedersachsen', lat: 52.97, lng: 10.56 },
  { name: 'Achim', state: 'Niedersachsen', lat: 53.01, lng: 9.03 },
  { name: 'Einbeck', state: 'Niedersachsen', lat: 51.82, lng: 9.87 },
  { name: 'Nienburg', state: 'Niedersachsen', lat: 52.64, lng: 9.22 },
  { name: 'Buxtehude', state: 'Niedersachsen', lat: 53.47, lng: 9.69 },
  { name: 'Springe', state: 'Niedersachsen', lat: 52.21, lng: 9.55 },
  { name: 'Papenburg', state: 'Niedersachsen', lat: 53.07, lng: 7.40 },
  { name: 'Verden', state: 'Niedersachsen', lat: 52.92, lng: 9.23 },

  // ─── Nordrhein-Westfalen ──────────────────────────────────────────────
  // Großstädte
  { name: 'Köln', state: 'Nordrhein-Westfalen', lat: 50.94, lng: 6.96 },
  { name: 'Düsseldorf', state: 'Nordrhein-Westfalen', lat: 51.23, lng: 6.77 },
  { name: 'Dortmund', state: 'Nordrhein-Westfalen', lat: 51.51, lng: 7.47 },
  { name: 'Essen', state: 'Nordrhein-Westfalen', lat: 51.46, lng: 7.01 },
  { name: 'Duisburg', state: 'Nordrhein-Westfalen', lat: 51.43, lng: 6.76 },
  { name: 'Bochum', state: 'Nordrhein-Westfalen', lat: 51.48, lng: 7.22 },
  { name: 'Wuppertal', state: 'Nordrhein-Westfalen', lat: 51.26, lng: 7.15 },
  { name: 'Bielefeld', state: 'Nordrhein-Westfalen', lat: 52.02, lng: 8.53 },
  { name: 'Bonn', state: 'Nordrhein-Westfalen', lat: 50.74, lng: 7.10 },
  { name: 'Münster', state: 'Nordrhein-Westfalen', lat: 51.96, lng: 7.63 },
  { name: 'Mönchengladbach', state: 'Nordrhein-Westfalen', lat: 51.18, lng: 6.44 },
  { name: 'Gelsenkirchen', state: 'Nordrhein-Westfalen', lat: 51.52, lng: 7.09 },
  { name: 'Aachen', state: 'Nordrhein-Westfalen', lat: 50.78, lng: 6.08 },
  { name: 'Krefeld', state: 'Nordrhein-Westfalen', lat: 51.34, lng: 6.56 },
  { name: 'Oberhausen', state: 'Nordrhein-Westfalen', lat: 51.47, lng: 6.85 },
  { name: 'Hagen', state: 'Nordrhein-Westfalen', lat: 51.36, lng: 7.47 },
  { name: 'Hamm', state: 'Nordrhein-Westfalen', lat: 51.68, lng: 7.82 },
  { name: 'Mülheim an der Ruhr', state: 'Nordrhein-Westfalen', lat: 51.43, lng: 6.88 },
  { name: 'Leverkusen', state: 'Nordrhein-Westfalen', lat: 51.05, lng: 7.02 },
  { name: 'Solingen', state: 'Nordrhein-Westfalen', lat: 51.17, lng: 7.08 },
  { name: 'Herne', state: 'Nordrhein-Westfalen', lat: 51.54, lng: 7.22 },
  { name: 'Neuss', state: 'Nordrhein-Westfalen', lat: 51.20, lng: 6.69 },
  { name: 'Paderborn', state: 'Nordrhein-Westfalen', lat: 51.72, lng: 8.75 },
  { name: 'Bottrop', state: 'Nordrhein-Westfalen', lat: 51.52, lng: 6.92 },
  { name: 'Recklinghausen', state: 'Nordrhein-Westfalen', lat: 51.61, lng: 7.20 },
  { name: 'Remscheid', state: 'Nordrhein-Westfalen', lat: 51.18, lng: 7.19 },
  { name: 'Moers', state: 'Nordrhein-Westfalen', lat: 51.45, lng: 6.63 },
  { name: 'Siegen', state: 'Nordrhein-Westfalen', lat: 50.87, lng: 8.02 },
  // Mittelstädte NRW
  { name: 'Bergisch Gladbach', state: 'Nordrhein-Westfalen', lat: 50.99, lng: 7.13 },
  { name: 'Witten', state: 'Nordrhein-Westfalen', lat: 51.44, lng: 7.34 },
  { name: 'Gütersloh', state: 'Nordrhein-Westfalen', lat: 51.91, lng: 8.38 },
  { name: 'Iserlohn', state: 'Nordrhein-Westfalen', lat: 51.37, lng: 7.70 },
  { name: 'Düren', state: 'Nordrhein-Westfalen', lat: 50.80, lng: 6.49 },
  { name: 'Ratingen', state: 'Nordrhein-Westfalen', lat: 51.30, lng: 6.85 },
  { name: 'Lünen', state: 'Nordrhein-Westfalen', lat: 51.62, lng: 7.53 },
  { name: 'Marl', state: 'Nordrhein-Westfalen', lat: 51.66, lng: 7.09 },
  { name: 'Velbert', state: 'Nordrhein-Westfalen', lat: 51.34, lng: 7.04 },
  { name: 'Minden', state: 'Nordrhein-Westfalen', lat: 52.29, lng: 8.92 },
  { name: 'Viersen', state: 'Nordrhein-Westfalen', lat: 51.25, lng: 6.39 },
  { name: 'Rheine', state: 'Nordrhein-Westfalen', lat: 52.28, lng: 7.44 },
  { name: 'Gladbeck', state: 'Nordrhein-Westfalen', lat: 51.57, lng: 6.99 },
  { name: 'Troisdorf', state: 'Nordrhein-Westfalen', lat: 50.82, lng: 7.16 },
  { name: 'Dorsten', state: 'Nordrhein-Westfalen', lat: 51.66, lng: 6.97 },
  { name: 'Detmold', state: 'Nordrhein-Westfalen', lat: 51.94, lng: 8.88 },
  { name: 'Castrop-Rauxel', state: 'Nordrhein-Westfalen', lat: 51.55, lng: 7.31 },
  { name: 'Arnsberg', state: 'Nordrhein-Westfalen', lat: 51.40, lng: 8.06 },
  { name: 'Bocholt', state: 'Nordrhein-Westfalen', lat: 51.84, lng: 6.62 },
  { name: 'Lüdenscheid', state: 'Nordrhein-Westfalen', lat: 51.22, lng: 7.63 },
  { name: 'Dinslaken', state: 'Nordrhein-Westfalen', lat: 51.57, lng: 6.74 },
  { name: 'Herford', state: 'Nordrhein-Westfalen', lat: 52.11, lng: 8.67 },
  { name: 'Herten', state: 'Nordrhein-Westfalen', lat: 51.60, lng: 7.14 },
  { name: 'Kerpen', state: 'Nordrhein-Westfalen', lat: 50.87, lng: 6.70 },
  { name: 'Unna', state: 'Nordrhein-Westfalen', lat: 51.53, lng: 7.69 },
  { name: 'Dormagen', state: 'Nordrhein-Westfalen', lat: 51.10, lng: 6.83 },
  { name: 'Grevenbroich', state: 'Nordrhein-Westfalen', lat: 51.09, lng: 6.59 },
  { name: 'Bergkamen', state: 'Nordrhein-Westfalen', lat: 51.62, lng: 7.63 },
  { name: 'Wesel', state: 'Nordrhein-Westfalen', lat: 51.66, lng: 6.62 },
  { name: 'Schwerte', state: 'Nordrhein-Westfalen', lat: 51.44, lng: 7.57 },
  { name: 'Langenfeld', state: 'Nordrhein-Westfalen', lat: 51.11, lng: 6.95 },
  { name: 'Meerbusch', state: 'Nordrhein-Westfalen', lat: 51.25, lng: 6.67 },
  { name: 'Stolberg', state: 'Nordrhein-Westfalen', lat: 50.77, lng: 6.23 },
  { name: 'Hilden', state: 'Nordrhein-Westfalen', lat: 51.17, lng: 6.93 },
  { name: 'Euskirchen', state: 'Nordrhein-Westfalen', lat: 50.66, lng: 6.79 },
  { name: 'Ahlen', state: 'Nordrhein-Westfalen', lat: 51.76, lng: 7.89 },
  { name: 'Kamen', state: 'Nordrhein-Westfalen', lat: 51.59, lng: 7.66 },
  { name: 'Pulheim', state: 'Nordrhein-Westfalen', lat: 50.99, lng: 6.81 },
  { name: 'Erkelenz', state: 'Nordrhein-Westfalen', lat: 51.08, lng: 6.31 },
  { name: 'Hattingen', state: 'Nordrhein-Westfalen', lat: 51.40, lng: 7.19 },
  { name: 'Hennef', state: 'Nordrhein-Westfalen', lat: 50.77, lng: 7.28 },
  { name: 'Lippstadt', state: 'Nordrhein-Westfalen', lat: 51.67, lng: 8.35 },
  { name: 'Kamp-Lintfort', state: 'Nordrhein-Westfalen', lat: 51.50, lng: 6.54 },
  { name: 'Sankt Augustin', state: 'Nordrhein-Westfalen', lat: 50.77, lng: 7.19 },
  { name: 'Siegburg', state: 'Nordrhein-Westfalen', lat: 50.80, lng: 7.21 },
  { name: 'Ibbenbüren', state: 'Nordrhein-Westfalen', lat: 52.28, lng: 7.72 },
  { name: 'Emmerich am Rhein', state: 'Nordrhein-Westfalen', lat: 51.83, lng: 6.24 },
  { name: 'Kleve', state: 'Nordrhein-Westfalen', lat: 51.79, lng: 6.14 },
  { name: 'Gummersbach', state: 'Nordrhein-Westfalen', lat: 51.03, lng: 7.56 },
  { name: 'Hürth', state: 'Nordrhein-Westfalen', lat: 50.87, lng: 6.87 },
  { name: 'Frechen', state: 'Nordrhein-Westfalen', lat: 50.91, lng: 6.81 },
  { name: 'Menden', state: 'Nordrhein-Westfalen', lat: 51.44, lng: 7.80 },
  { name: 'Beckum', state: 'Nordrhein-Westfalen', lat: 51.76, lng: 8.04 },
  { name: 'Werne', state: 'Nordrhein-Westfalen', lat: 51.66, lng: 7.63 },
  { name: 'Mechernich', state: 'Nordrhein-Westfalen', lat: 50.59, lng: 6.65 },
  { name: 'Porta Westfalica', state: 'Nordrhein-Westfalen', lat: 52.24, lng: 8.92 },
  { name: 'Bad Oeynhausen', state: 'Nordrhein-Westfalen', lat: 52.21, lng: 8.80 },
  { name: 'Oer-Erkenschwick', state: 'Nordrhein-Westfalen', lat: 51.64, lng: 7.26 },
  { name: 'Waltrop', state: 'Nordrhein-Westfalen', lat: 51.62, lng: 7.40 },
  { name: 'Sprockhövel', state: 'Nordrhein-Westfalen', lat: 51.35, lng: 7.25 },
  { name: 'Coesfeld', state: 'Nordrhein-Westfalen', lat: 51.94, lng: 7.17 },
  { name: 'Willich', state: 'Nordrhein-Westfalen', lat: 51.26, lng: 6.55 },
  { name: 'Greven', state: 'Nordrhein-Westfalen', lat: 52.09, lng: 7.61 },
  { name: 'Emsdetten', state: 'Nordrhein-Westfalen', lat: 52.17, lng: 7.53 },
  { name: 'Schwelm', state: 'Nordrhein-Westfalen', lat: 51.29, lng: 7.29 },
  { name: 'Heiligenhaus', state: 'Nordrhein-Westfalen', lat: 51.33, lng: 6.97 },

  // ─── Hessen ───────────────────────────────────────────────────────────
  { name: 'Frankfurt am Main', state: 'Hessen', lat: 50.11, lng: 8.68 },
  { name: 'Wiesbaden', state: 'Hessen', lat: 50.08, lng: 8.24 },
  { name: 'Kassel', state: 'Hessen', lat: 51.32, lng: 9.50 },
  { name: 'Darmstadt', state: 'Hessen', lat: 49.87, lng: 8.65 },
  { name: 'Offenbach am Main', state: 'Hessen', lat: 50.10, lng: 8.76 },
  { name: 'Hanau', state: 'Hessen', lat: 50.13, lng: 8.92 },
  { name: 'Gießen', state: 'Hessen', lat: 50.58, lng: 8.68 },
  { name: 'Marburg', state: 'Hessen', lat: 50.81, lng: 8.77 },
  { name: 'Fulda', state: 'Hessen', lat: 50.55, lng: 9.68 },
  { name: 'Rüsselsheim', state: 'Hessen', lat: 49.99, lng: 8.41 },
  { name: 'Bad Homburg', state: 'Hessen', lat: 50.23, lng: 8.62 },
  { name: 'Wetzlar', state: 'Hessen', lat: 50.56, lng: 8.50 },
  { name: 'Oberursel', state: 'Hessen', lat: 50.20, lng: 8.58 },
  { name: 'Rodgau', state: 'Hessen', lat: 50.03, lng: 8.88 },
  { name: 'Dreieich', state: 'Hessen', lat: 50.02, lng: 8.70 },
  { name: 'Bensheim', state: 'Hessen', lat: 49.68, lng: 8.62 },
  { name: 'Langen', state: 'Hessen', lat: 49.99, lng: 8.68 },
  { name: 'Neu-Isenburg', state: 'Hessen', lat: 50.05, lng: 8.69 },
  { name: 'Limburg an der Lahn', state: 'Hessen', lat: 50.39, lng: 8.07 },
  { name: 'Dietzenbach', state: 'Hessen', lat: 50.01, lng: 8.78 },
  { name: 'Viernheim', state: 'Hessen', lat: 49.54, lng: 8.58 },
  { name: 'Taunusstein', state: 'Hessen', lat: 50.14, lng: 8.16 },
  { name: 'Lampertheim', state: 'Hessen', lat: 49.60, lng: 8.47 },
  { name: 'Mörfelden-Walldorf', state: 'Hessen', lat: 49.99, lng: 8.58 },
  { name: 'Bad Vilbel', state: 'Hessen', lat: 50.18, lng: 8.74 },
  { name: 'Friedberg', state: 'Hessen', lat: 50.33, lng: 8.76 },
  { name: 'Korbach', state: 'Hessen', lat: 51.28, lng: 8.87 },
  { name: 'Hofheim am Taunus', state: 'Hessen', lat: 50.09, lng: 8.45 },
  { name: 'Baunatal', state: 'Hessen', lat: 51.26, lng: 9.42 },
  { name: 'Kelkheim', state: 'Hessen', lat: 50.14, lng: 8.45 },
  { name: 'Groß-Gerau', state: 'Hessen', lat: 49.92, lng: 8.48 },
  { name: 'Hattersheim', state: 'Hessen', lat: 50.07, lng: 8.49 },
  { name: 'Eschborn', state: 'Hessen', lat: 50.14, lng: 8.57 },

  // ─── Rheinland-Pfalz ─────────────────────────────────────────────────
  { name: 'Mainz', state: 'Rheinland-Pfalz', lat: 50.00, lng: 8.27 },
  { name: 'Ludwigshafen', state: 'Rheinland-Pfalz', lat: 49.48, lng: 8.44 },
  { name: 'Koblenz', state: 'Rheinland-Pfalz', lat: 50.36, lng: 7.59 },
  { name: 'Trier', state: 'Rheinland-Pfalz', lat: 49.76, lng: 6.64 },
  { name: 'Kaiserslautern', state: 'Rheinland-Pfalz', lat: 49.44, lng: 7.77 },
  { name: 'Worms', state: 'Rheinland-Pfalz', lat: 49.63, lng: 8.36 },
  { name: 'Neuwied', state: 'Rheinland-Pfalz', lat: 50.43, lng: 7.46 },
  { name: 'Neustadt an der Weinstraße', state: 'Rheinland-Pfalz', lat: 49.35, lng: 8.14 },
  { name: 'Bad Kreuznach', state: 'Rheinland-Pfalz', lat: 49.84, lng: 7.87 },
  { name: 'Speyer', state: 'Rheinland-Pfalz', lat: 49.32, lng: 8.43 },
  { name: 'Frankenthal', state: 'Rheinland-Pfalz', lat: 49.53, lng: 8.35 },
  { name: 'Landau', state: 'Rheinland-Pfalz', lat: 49.20, lng: 8.12 },
  { name: 'Pirmasens', state: 'Rheinland-Pfalz', lat: 49.20, lng: 7.60 },
  { name: 'Zweibrücken', state: 'Rheinland-Pfalz', lat: 49.25, lng: 7.37 },
  { name: 'Andernach', state: 'Rheinland-Pfalz', lat: 50.44, lng: 7.40 },
  { name: 'Idar-Oberstein', state: 'Rheinland-Pfalz', lat: 49.71, lng: 7.31 },
  { name: 'Bingen', state: 'Rheinland-Pfalz', lat: 49.97, lng: 7.90 },
  { name: 'Ingelheim', state: 'Rheinland-Pfalz', lat: 49.97, lng: 8.06 },
  { name: 'Mayen', state: 'Rheinland-Pfalz', lat: 50.33, lng: 7.22 },
  { name: 'Lahnstein', state: 'Rheinland-Pfalz', lat: 50.30, lng: 7.61 },
  { name: 'Germersheim', state: 'Rheinland-Pfalz', lat: 49.22, lng: 8.37 },

  // ─── Baden-Württemberg ────────────────────────────────────────────────
  { name: 'Stuttgart', state: 'Baden-Württemberg', lat: 48.78, lng: 9.18 },
  { name: 'Mannheim', state: 'Baden-Württemberg', lat: 49.49, lng: 8.47 },
  { name: 'Karlsruhe', state: 'Baden-Württemberg', lat: 49.01, lng: 8.40 },
  { name: 'Freiburg', state: 'Baden-Württemberg', lat: 47.99, lng: 7.85 },
  { name: 'Heidelberg', state: 'Baden-Württemberg', lat: 49.40, lng: 8.69 },
  { name: 'Ulm', state: 'Baden-Württemberg', lat: 48.40, lng: 9.99 },
  { name: 'Heilbronn', state: 'Baden-Württemberg', lat: 49.14, lng: 9.22 },
  { name: 'Pforzheim', state: 'Baden-Württemberg', lat: 48.89, lng: 8.70 },
  { name: 'Reutlingen', state: 'Baden-Württemberg', lat: 48.49, lng: 9.21 },
  { name: 'Esslingen', state: 'Baden-Württemberg', lat: 48.74, lng: 9.31 },
  { name: 'Ludwigsburg', state: 'Baden-Württemberg', lat: 48.90, lng: 9.19 },
  { name: 'Tübingen', state: 'Baden-Württemberg', lat: 48.52, lng: 9.06 },
  { name: 'Villingen-Schwenningen', state: 'Baden-Württemberg', lat: 48.06, lng: 8.45 },
  { name: 'Konstanz', state: 'Baden-Württemberg', lat: 47.66, lng: 9.18 },
  { name: 'Sindelfingen', state: 'Baden-Württemberg', lat: 48.71, lng: 9.00 },
  { name: 'Schwäbisch Gmünd', state: 'Baden-Württemberg', lat: 48.80, lng: 9.80 },
  { name: 'Ravensburg', state: 'Baden-Württemberg', lat: 47.78, lng: 9.61 },
  { name: 'Böblingen', state: 'Baden-Württemberg', lat: 48.69, lng: 9.01 },
  { name: 'Göppingen', state: 'Baden-Württemberg', lat: 48.70, lng: 9.65 },
  { name: 'Offenburg', state: 'Baden-Württemberg', lat: 48.47, lng: 7.94 },
  { name: 'Friedrichshafen', state: 'Baden-Württemberg', lat: 47.65, lng: 9.48 },
  { name: 'Aalen', state: 'Baden-Württemberg', lat: 48.84, lng: 10.09 },
  { name: 'Lörrach', state: 'Baden-Württemberg', lat: 47.62, lng: 7.66 },
  { name: 'Waiblingen', state: 'Baden-Württemberg', lat: 48.83, lng: 9.32 },
  { name: 'Baden-Baden', state: 'Baden-Württemberg', lat: 48.76, lng: 8.24 },
  { name: 'Heidenheim', state: 'Baden-Württemberg', lat: 48.68, lng: 10.15 },
  { name: 'Rastatt', state: 'Baden-Württemberg', lat: 48.86, lng: 8.21 },
  { name: 'Leonberg', state: 'Baden-Württemberg', lat: 48.80, lng: 9.02 },
  { name: 'Lahr', state: 'Baden-Württemberg', lat: 48.34, lng: 7.87 },
  { name: 'Weinheim', state: 'Baden-Württemberg', lat: 49.55, lng: 8.67 },
  { name: 'Bruchsal', state: 'Baden-Württemberg', lat: 49.13, lng: 8.60 },
  { name: 'Schwäbisch Hall', state: 'Baden-Württemberg', lat: 49.11, lng: 9.74 },
  { name: 'Neckarsulm', state: 'Baden-Württemberg', lat: 49.19, lng: 9.23 },
  { name: 'Ettlingen', state: 'Baden-Württemberg', lat: 48.94, lng: 8.41 },
  { name: 'Bietigheim-Bissingen', state: 'Baden-Württemberg', lat: 48.96, lng: 9.13 },
  { name: 'Fellbach', state: 'Baden-Württemberg', lat: 48.81, lng: 9.28 },
  { name: 'Leinfelden-Echterdingen', state: 'Baden-Württemberg', lat: 48.69, lng: 9.17 },
  { name: 'Filderstadt', state: 'Baden-Württemberg', lat: 48.66, lng: 9.22 },
  { name: 'Crailsheim', state: 'Baden-Württemberg', lat: 49.13, lng: 10.07 },
  { name: 'Backnang', state: 'Baden-Württemberg', lat: 48.95, lng: 9.43 },
  { name: 'Rottenburg', state: 'Baden-Württemberg', lat: 48.48, lng: 8.93 },
  { name: 'Singen', state: 'Baden-Württemberg', lat: 47.76, lng: 8.84 },
  { name: 'Nürtingen', state: 'Baden-Württemberg', lat: 48.63, lng: 9.34 },
  { name: 'Weil am Rhein', state: 'Baden-Württemberg', lat: 47.59, lng: 7.62 },
  { name: 'Kirchheim unter Teck', state: 'Baden-Württemberg', lat: 48.65, lng: 9.45 },
  { name: 'Ostfildern', state: 'Baden-Württemberg', lat: 48.73, lng: 9.25 },
  { name: 'Rheinfelden', state: 'Baden-Württemberg', lat: 47.56, lng: 7.79 },
  { name: 'Herrenberg', state: 'Baden-Württemberg', lat: 48.60, lng: 8.87 },
  { name: 'Schorndorf', state: 'Baden-Württemberg', lat: 48.80, lng: 9.53 },
  { name: 'Wangen im Allgäu', state: 'Baden-Württemberg', lat: 47.69, lng: 9.83 },
  { name: 'Kornwestheim', state: 'Baden-Württemberg', lat: 48.86, lng: 9.18 },

  // ─── Bayern ───────────────────────────────────────────────────────────
  { name: 'München', state: 'Bayern', lat: 48.14, lng: 11.58 },
  { name: 'Nürnberg', state: 'Bayern', lat: 49.45, lng: 11.08 },
  { name: 'Augsburg', state: 'Bayern', lat: 48.37, lng: 10.90 },
  { name: 'Regensburg', state: 'Bayern', lat: 49.01, lng: 12.10 },
  { name: 'Ingolstadt', state: 'Bayern', lat: 48.76, lng: 11.42 },
  { name: 'Würzburg', state: 'Bayern', lat: 49.79, lng: 9.94 },
  { name: 'Fürth', state: 'Bayern', lat: 49.48, lng: 10.99 },
  { name: 'Erlangen', state: 'Bayern', lat: 49.60, lng: 11.01 },
  { name: 'Bamberg', state: 'Bayern', lat: 49.89, lng: 10.89 },
  { name: 'Bayreuth', state: 'Bayern', lat: 49.95, lng: 11.58 },
  { name: 'Aschaffenburg', state: 'Bayern', lat: 49.98, lng: 9.15 },
  { name: 'Landshut', state: 'Bayern', lat: 48.54, lng: 12.15 },
  { name: 'Kempten', state: 'Bayern', lat: 47.73, lng: 10.32 },
  { name: 'Rosenheim', state: 'Bayern', lat: 47.86, lng: 12.13 },
  { name: 'Schweinfurt', state: 'Bayern', lat: 50.05, lng: 10.23 },
  { name: 'Passau', state: 'Bayern', lat: 48.57, lng: 13.46 },
  { name: 'Freising', state: 'Bayern', lat: 48.40, lng: 11.75 },
  { name: 'Straubing', state: 'Bayern', lat: 48.88, lng: 12.57 },
  { name: 'Dachau', state: 'Bayern', lat: 48.26, lng: 11.43 },
  { name: 'Hof', state: 'Bayern', lat: 50.31, lng: 11.91 },
  { name: 'Memmingen', state: 'Bayern', lat: 47.99, lng: 10.18 },
  { name: 'Kaufbeuren', state: 'Bayern', lat: 47.88, lng: 10.62 },
  { name: 'Weiden in der Oberpfalz', state: 'Bayern', lat: 49.68, lng: 12.16 },
  { name: 'Amberg', state: 'Bayern', lat: 49.44, lng: 11.85 },
  { name: 'Ansbach', state: 'Bayern', lat: 49.30, lng: 10.57 },
  { name: 'Coburg', state: 'Bayern', lat: 50.26, lng: 10.96 },
  { name: 'Schwabach', state: 'Bayern', lat: 49.33, lng: 11.02 },
  { name: 'Neumarkt in der Oberpfalz', state: 'Bayern', lat: 49.28, lng: 11.46 },
  { name: 'Deggendorf', state: 'Bayern', lat: 48.84, lng: 12.96 },
  { name: 'Neu-Ulm', state: 'Bayern', lat: 48.39, lng: 10.01 },
  { name: 'Germering', state: 'Bayern', lat: 48.13, lng: 11.37 },
  { name: 'Fürstenfeldbruck', state: 'Bayern', lat: 48.18, lng: 11.26 },
  { name: 'Erding', state: 'Bayern', lat: 48.31, lng: 11.91 },
  { name: 'Starnberg', state: 'Bayern', lat: 47.99, lng: 11.34 },
  { name: 'Unterschleißheim', state: 'Bayern', lat: 48.28, lng: 11.58 },
  { name: 'Ottobrunn', state: 'Bayern', lat: 48.07, lng: 11.67 },
  { name: 'Sonthofen', state: 'Bayern', lat: 47.52, lng: 10.28 },
  { name: 'Traunstein', state: 'Bayern', lat: 47.87, lng: 12.64 },
  { name: 'Lauf an der Pegnitz', state: 'Bayern', lat: 49.51, lng: 11.28 },
  { name: 'Herzogenaurach', state: 'Bayern', lat: 49.57, lng: 10.89 },
  { name: 'Forchheim', state: 'Bayern', lat: 49.72, lng: 11.06 },
  { name: 'Neuburg an der Donau', state: 'Bayern', lat: 48.73, lng: 11.19 },
  { name: 'Günzburg', state: 'Bayern', lat: 48.46, lng: 10.27 },
  { name: 'Lindau', state: 'Bayern', lat: 47.55, lng: 9.68 },
  { name: 'Weilheim', state: 'Bayern', lat: 47.84, lng: 11.14 },
  { name: 'Garmisch-Partenkirchen', state: 'Bayern', lat: 47.50, lng: 11.10 },
  { name: 'Olching', state: 'Bayern', lat: 48.20, lng: 11.33 },
  { name: 'Vaterstetten', state: 'Bayern', lat: 48.11, lng: 11.77 },
  { name: 'Kitzingen', state: 'Bayern', lat: 49.73, lng: 10.17 },
  { name: 'Haar', state: 'Bayern', lat: 48.11, lng: 11.72 },
  { name: 'Schwandorf', state: 'Bayern', lat: 49.33, lng: 12.11 },
  { name: 'Königsbrunn', state: 'Bayern', lat: 48.27, lng: 10.89 },
  { name: 'Friedberg', state: 'Bayern', lat: 48.36, lng: 10.98 },
  { name: 'Garching', state: 'Bayern', lat: 48.25, lng: 11.65 },
  { name: 'Unterhaching', state: 'Bayern', lat: 48.07, lng: 11.62 },

  // ─── Saarland ─────────────────────────────────────────────────────────
  { name: 'Saarbrücken', state: 'Saarland', lat: 49.24, lng: 6.99 },
  { name: 'Neunkirchen', state: 'Saarland', lat: 49.35, lng: 7.18 },
  { name: 'Homburg', state: 'Saarland', lat: 49.32, lng: 7.34 },
  { name: 'Völklingen', state: 'Saarland', lat: 49.25, lng: 6.86 },
  { name: 'Sankt Ingbert', state: 'Saarland', lat: 49.28, lng: 7.12 },
  { name: 'Saarlouis', state: 'Saarland', lat: 49.31, lng: 6.75 },
  { name: 'Merzig', state: 'Saarland', lat: 49.44, lng: 6.64 },
  { name: 'Sankt Wendel', state: 'Saarland', lat: 49.47, lng: 7.17 },
  { name: 'Dillingen', state: 'Saarland', lat: 49.36, lng: 6.73 },
  { name: 'Blieskastel', state: 'Saarland', lat: 49.24, lng: 7.25 },

  // ─── Brandenburg ──────────────────────────────────────────────────────
  { name: 'Potsdam', state: 'Brandenburg', lat: 52.40, lng: 13.07 },
  { name: 'Cottbus', state: 'Brandenburg', lat: 51.76, lng: 14.33 },
  { name: 'Brandenburg an der Havel', state: 'Brandenburg', lat: 52.41, lng: 12.56 },
  { name: 'Frankfurt (Oder)', state: 'Brandenburg', lat: 52.35, lng: 14.55 },
  { name: 'Oranienburg', state: 'Brandenburg', lat: 52.76, lng: 13.24 },
  { name: 'Falkensee', state: 'Brandenburg', lat: 52.56, lng: 13.09 },
  { name: 'Bernau', state: 'Brandenburg', lat: 52.68, lng: 13.59 },
  { name: 'Eberswalde', state: 'Brandenburg', lat: 52.83, lng: 13.82 },
  { name: 'Fürstenwalde', state: 'Brandenburg', lat: 52.36, lng: 14.06 },
  { name: 'Königs Wusterhausen', state: 'Brandenburg', lat: 52.30, lng: 13.63 },
  { name: 'Schwedt', state: 'Brandenburg', lat: 53.06, lng: 14.28 },
  { name: 'Neuruppin', state: 'Brandenburg', lat: 52.92, lng: 12.80 },
  { name: 'Hennigsdorf', state: 'Brandenburg', lat: 52.64, lng: 13.20 },
  { name: 'Teltow', state: 'Brandenburg', lat: 52.40, lng: 13.27 },
  { name: 'Werder', state: 'Brandenburg', lat: 52.38, lng: 12.93 },
  { name: 'Hohen Neuendorf', state: 'Brandenburg', lat: 52.67, lng: 13.28 },
  { name: 'Senftenberg', state: 'Brandenburg', lat: 51.53, lng: 14.00 },
  { name: 'Luckenwalde', state: 'Brandenburg', lat: 52.09, lng: 13.17 },
  { name: 'Strausberg', state: 'Brandenburg', lat: 52.58, lng: 13.88 },
  { name: 'Ludwigsfelde', state: 'Brandenburg', lat: 52.30, lng: 13.25 },
  { name: 'Spremberg', state: 'Brandenburg', lat: 51.57, lng: 14.37 },

  // ─── Mecklenburg-Vorpommern ───────────────────────────────────────────
  { name: 'Rostock', state: 'Mecklenburg-Vorpommern', lat: 54.09, lng: 12.10 },
  { name: 'Schwerin', state: 'Mecklenburg-Vorpommern', lat: 53.63, lng: 11.41 },
  { name: 'Neubrandenburg', state: 'Mecklenburg-Vorpommern', lat: 53.56, lng: 13.26 },
  { name: 'Stralsund', state: 'Mecklenburg-Vorpommern', lat: 54.31, lng: 13.09 },
  { name: 'Greifswald', state: 'Mecklenburg-Vorpommern', lat: 54.09, lng: 13.39 },
  { name: 'Wismar', state: 'Mecklenburg-Vorpommern', lat: 53.89, lng: 11.47 },
  { name: 'Güstrow', state: 'Mecklenburg-Vorpommern', lat: 53.80, lng: 12.18 },
  { name: 'Waren', state: 'Mecklenburg-Vorpommern', lat: 53.52, lng: 12.68 },
  { name: 'Parchim', state: 'Mecklenburg-Vorpommern', lat: 53.43, lng: 11.85 },
  { name: 'Anklam', state: 'Mecklenburg-Vorpommern', lat: 53.86, lng: 13.69 },
  { name: 'Bergen auf Rügen', state: 'Mecklenburg-Vorpommern', lat: 54.42, lng: 13.43 },
  { name: 'Ribnitz-Damgarten', state: 'Mecklenburg-Vorpommern', lat: 54.25, lng: 12.43 },

  // ─── Sachsen ──────────────────────────────────────────────────────────
  { name: 'Leipzig', state: 'Sachsen', lat: 51.34, lng: 12.37 },
  { name: 'Dresden', state: 'Sachsen', lat: 51.05, lng: 13.74 },
  { name: 'Chemnitz', state: 'Sachsen', lat: 50.83, lng: 12.92 },
  { name: 'Zwickau', state: 'Sachsen', lat: 50.72, lng: 12.49 },
  { name: 'Plauen', state: 'Sachsen', lat: 50.49, lng: 12.13 },
  { name: 'Görlitz', state: 'Sachsen', lat: 51.15, lng: 14.99 },
  { name: 'Freiberg', state: 'Sachsen', lat: 50.92, lng: 13.34 },
  { name: 'Bautzen', state: 'Sachsen', lat: 51.18, lng: 14.42 },
  { name: 'Pirna', state: 'Sachsen', lat: 50.96, lng: 13.94 },
  { name: 'Freital', state: 'Sachsen', lat: 51.00, lng: 13.65 },
  { name: 'Radebeul', state: 'Sachsen', lat: 51.10, lng: 13.66 },
  { name: 'Meißen', state: 'Sachsen', lat: 51.16, lng: 13.47 },
  { name: 'Riesa', state: 'Sachsen', lat: 51.31, lng: 13.29 },
  { name: 'Markkleeberg', state: 'Sachsen', lat: 51.28, lng: 12.37 },
  { name: 'Coswig', state: 'Sachsen', lat: 51.13, lng: 13.58 },
  { name: 'Döbeln', state: 'Sachsen', lat: 51.12, lng: 13.11 },
  { name: 'Hoyerswerda', state: 'Sachsen', lat: 51.44, lng: 14.25 },
  { name: 'Delitzsch', state: 'Sachsen', lat: 51.53, lng: 12.34 },
  { name: 'Limbach-Oberfrohna', state: 'Sachsen', lat: 50.86, lng: 12.76 },
  { name: 'Crimmitschau', state: 'Sachsen', lat: 50.81, lng: 12.39 },
  { name: 'Annaberg-Buchholz', state: 'Sachsen', lat: 50.58, lng: 13.00 },
  { name: 'Grimma', state: 'Sachsen', lat: 51.24, lng: 12.72 },
  { name: 'Werdau', state: 'Sachsen', lat: 50.73, lng: 12.37 },
  { name: 'Schkeuditz', state: 'Sachsen', lat: 51.40, lng: 12.22 },
  { name: 'Torgau', state: 'Sachsen', lat: 51.56, lng: 13.01 },

  // ─── Sachsen-Anhalt ───────────────────────────────────────────────────
  { name: 'Halle', state: 'Sachsen-Anhalt', lat: 51.48, lng: 11.97 },
  { name: 'Magdeburg', state: 'Sachsen-Anhalt', lat: 52.13, lng: 11.63 },
  { name: 'Dessau-Roßlau', state: 'Sachsen-Anhalt', lat: 51.83, lng: 12.25 },
  { name: 'Wittenberg', state: 'Sachsen-Anhalt', lat: 51.87, lng: 12.65 },
  { name: 'Stendal', state: 'Sachsen-Anhalt', lat: 52.60, lng: 11.86 },
  { name: 'Halberstadt', state: 'Sachsen-Anhalt', lat: 51.90, lng: 11.06 },
  { name: 'Weißenfels', state: 'Sachsen-Anhalt', lat: 51.20, lng: 11.97 },
  { name: 'Wernigerode', state: 'Sachsen-Anhalt', lat: 51.83, lng: 10.79 },
  { name: 'Bernburg', state: 'Sachsen-Anhalt', lat: 51.80, lng: 11.74 },
  { name: 'Bitterfeld-Wolfen', state: 'Sachsen-Anhalt', lat: 51.62, lng: 12.33 },
  { name: 'Aschersleben', state: 'Sachsen-Anhalt', lat: 51.76, lng: 11.46 },
  { name: 'Schönebeck', state: 'Sachsen-Anhalt', lat: 52.02, lng: 11.73 },
  { name: 'Naumburg', state: 'Sachsen-Anhalt', lat: 51.15, lng: 11.81 },
  { name: 'Sangerhausen', state: 'Sachsen-Anhalt', lat: 51.47, lng: 11.30 },
  { name: 'Merseburg', state: 'Sachsen-Anhalt', lat: 51.36, lng: 11.99 },
  { name: 'Quedlinburg', state: 'Sachsen-Anhalt', lat: 51.79, lng: 11.15 },
  { name: 'Staßfurt', state: 'Sachsen-Anhalt', lat: 51.86, lng: 11.58 },
  { name: 'Zeitz', state: 'Sachsen-Anhalt', lat: 51.05, lng: 12.14 },
  { name: 'Köthen', state: 'Sachsen-Anhalt', lat: 51.75, lng: 11.97 },
  { name: 'Burg', state: 'Sachsen-Anhalt', lat: 52.27, lng: 11.86 },

  // ─── Thüringen ────────────────────────────────────────────────────────
  { name: 'Erfurt', state: 'Thüringen', lat: 50.98, lng: 11.03 },
  { name: 'Jena', state: 'Thüringen', lat: 50.93, lng: 11.59 },
  { name: 'Gera', state: 'Thüringen', lat: 50.88, lng: 12.08 },
  { name: 'Weimar', state: 'Thüringen', lat: 50.98, lng: 11.33 },
  { name: 'Gotha', state: 'Thüringen', lat: 50.95, lng: 10.70 },
  { name: 'Nordhausen', state: 'Thüringen', lat: 51.50, lng: 10.79 },
  { name: 'Eisenach', state: 'Thüringen', lat: 50.97, lng: 10.32 },
  { name: 'Suhl', state: 'Thüringen', lat: 50.61, lng: 10.69 },
  { name: 'Altenburg', state: 'Thüringen', lat: 50.99, lng: 12.44 },
  { name: 'Mühlhausen', state: 'Thüringen', lat: 51.21, lng: 10.45 },
  { name: 'Ilmenau', state: 'Thüringen', lat: 50.68, lng: 10.92 },
  { name: 'Arnstadt', state: 'Thüringen', lat: 50.83, lng: 10.95 },
  { name: 'Rudolstadt', state: 'Thüringen', lat: 50.72, lng: 11.34 },
  { name: 'Apolda', state: 'Thüringen', lat: 51.02, lng: 11.51 },
  { name: 'Sondershausen', state: 'Thüringen', lat: 51.37, lng: 10.87 },
  { name: 'Saalfeld', state: 'Thüringen', lat: 50.65, lng: 11.36 },
  { name: 'Greiz', state: 'Thüringen', lat: 50.66, lng: 12.20 },
  { name: 'Sonneberg', state: 'Thüringen', lat: 50.36, lng: 11.18 },
  { name: 'Meiningen', state: 'Thüringen', lat: 50.57, lng: 10.42 },
  { name: 'Schmalkalden', state: 'Thüringen', lat: 50.72, lng: 10.45 },
  { name: 'Bad Langensalza', state: 'Thüringen', lat: 51.11, lng: 10.65 },
  { name: 'Heilbad Heiligenstadt', state: 'Thüringen', lat: 51.38, lng: 10.14 },
];

/**
 * Haversine formula: computes the great-circle distance in km between
 * two points specified by latitude/longitude in decimal degrees.
 */
function haversineDistance(
  lat1: number,
  lng1: number,
  lat2: number,
  lng2: number,
): number {
  const R = 6371; // Earth radius in km
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLng = ((lng2 - lng1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLng / 2) *
      Math.sin(dLng / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return R * c;
}

/**
 * Find all cities within a given radius (km) of a center point.
 * Results are sorted by distance (nearest first).
 */
export function findCitiesInRadius(
  centerLat: number,
  centerLng: number,
  radiusKm: number,
): City[] {
  return GERMAN_CITIES.filter((city) => {
    const dist = haversineDistance(centerLat, centerLng, city.lat, city.lng);
    return dist <= radiusKm;
  }).sort((a, b) => {
    const distA = haversineDistance(centerLat, centerLng, a.lat, a.lng);
    const distB = haversineDistance(centerLat, centerLng, b.lat, b.lng);
    return distA - distB;
  });
}

/**
 * Get all cities belonging to a given Bundesland.
 * The state name must match exactly (case-sensitive).
 */
export function getCitiesByState(state: string): City[] {
  return GERMAN_CITIES.filter((city) => city.state === state);
}
