export interface CategoryMapping {
  id: string;
  name: string;
  keywords: string[];
  scrapeKeywords: string[];
}

export const CATEGORIES: CategoryMapping[] = [
  {
    id: 'handwerk',
    name: 'Handwerk',
    keywords: [
      'elektriker', 'elektro', 'elektrik', 'elektroinstallation', 'elektrotechnik',
      'klempner', 'sanitär', 'heizung', 'shk', 'installateur',
      'maler', 'malerbetrieb', 'lackierer', 'anstreicher',
      'dachdecker', 'dach', 'bedachung',
      'schreiner', 'tischler', 'möbel', 'holz',
      'schlosser', 'metallbau', 'schweißer',
      'fliesenleger', 'fliesen', 'bodenleger',
      'maurer', 'maurerarbeiten', 'trockenbau',
      'zimmerer', 'zimmermann', 'holzbau',
      'glaser', 'glaserei',
      'stuckateur', 'putz', 'verputzer',
      'kfz', 'autowerkstatt', 'auto', 'mechaniker', 'karosserie',
      'gärtner', 'garten', 'landschaftsbau', 'gartenbau', 'galabau',
      'gebäudereinigung', 'reinigung', 'reinigungsfirma',
      'umzug', 'umzugsunternehmen', 'transport',
      'hausmeister', 'facility', 'gebäudemanagement',
      'rollladen', 'jalousie', 'sonnenschutz', 'markise',
      'aufzug', 'fahrstuhl', 'lift',
      'klimaanlage', 'klima', 'kältetechnik', 'lüftung',
      'photovoltaik', 'solar', 'solaranlage', 'pv',
      'brandschutz', 'feuerlöscher',
      'schlüsseldienst', 'sicherheitstechnik',
    ],
    scrapeKeywords: [
      'Elektriker',
      'Elektroinstallation',
      'Sanitär Heizung',
      'Klempner',
      'Heizungsbauer',
      'Installateur',
      'Maler',
      'Lackierer',
      'Dachdecker',
      'Schreiner',
      'Tischler',
      'Schlosser',
      'Metallbau',
      'Fliesenleger',
      'Bodenleger',
      'Parkettleger',
      'Maurer',
      'Trockenbau',
      'Zimmerei',
      'Holzbau',
      'Glaser',
      'Glaserei',
      'Stuckateur',
      'KFZ Werkstatt',
      'Autowerkstatt',
      'Karosseriebau',
      'Autolackierer',
      'Garten und Landschaftsbau',
      'Gärtner',
      'Baumfällung Baumpflege',
      'Gebäudereinigung',
      'Industriereinigung',
      'Umzugsunternehmen',
      'Hausmeisterservice',
      'Facility Management',
      'Rollladen Sonnenschutz',
      'Markisen',
      'Aufzug Montage',
      'Klimaanlage',
      'Kältetechnik',
      'Lüftungstechnik',
      'Photovoltaik',
      'Solaranlage',
      'Brandschutz',
      'Schlüsseldienst',
      'Sicherheitstechnik',
      'Steinmetz',
      'Ofenbauer',
      'Kaminbauer',
      'Schornsteinfeger',
      'Estrichleger',
      'Spengler',
      'Rohrreinigung',
      'Kanalsanierung',
      'Entrümpelung',
      'Schädlingsbekämpfung',
      'Gerüstbau',
      'Abbruchunternehmen',
      'Pflasterarbeiten',
      'Betonbau',
      'Schweißtechnik',
      'Zaunbau',
      'Tor und Zaunbau',
      'Fenster Türen Montage',
      'Fensterbauer',
      'Raumausstatter',
      'Polsterer',
      'Parkett schleifen',
      'Estrich',
      'Wärmedämmung',
      'Fassade',
      'Putzarbeiten',
      'Dachrinne',
      'Blitzschutz',
      'Alarmanlagen',
      'Videoüberwachung',
      'Elektromontage',
      'Netzwerktechnik',
      'Haustechnik',
      'Gebäudetechnik',
      'Poolbau',
      'Brunnenbau',
      'Winterdienst',
      'Straßenreinigung',
    ],
  },
  {
    id: 'gesundheit',
    name: 'Gesundheit & Medizin',
    keywords: [
      'zahnarzt', 'zahnklinik', 'dental', 'kieferorthopäde', 'zahnmedizin',
      'arzt', 'praxis', 'hausarzt', 'allgemeinarzt', 'facharzt',
      'physiotherapie', 'physiotherapeut', 'krankengymnastik',
      'orthopäde', 'orthopädie',
      'augenarzt', 'optiker', 'optik',
      'hno', 'hals-nasen-ohren',
      'dermatologie', 'hautarzt',
      'psychotherapie', 'psychologe', 'therapeut',
      'heilpraktiker', 'naturheilkunde', 'alternativmedizin',
      'osteopathie', 'osteopath', 'chiropraktik',
      'logopädie', 'logopäde', 'sprachtherapie',
      'ergotherapie', 'ergotherapeut',
      'apotheke', 'pharma',
      'pflegedienst', 'pflege', 'altenpflege', 'ambulant',
      'tierarzt', 'tierarztpraxis', 'tierklinik', 'veterinär',
      'labor', 'labormedizin',
      'radiologie', 'röntgen', 'mrt',
      'kardiologe', 'kardiologie', 'herz',
      'urologie', 'urologe',
      'gynäkologie', 'frauenarzt', 'gynäkologe',
    ],
    scrapeKeywords: [
      'Zahnarzt', 'Kieferorthopäde', 'Hausarzt', 'Allgemeinarzt',
      'Orthopäde', 'Augenarzt', 'HNO Arzt', 'Hautarzt',
      'Physiotherapie', 'Krankengymnastik', 'Osteopathie',
      'Psychotherapeut', 'Psychologe', 'Heilpraktiker',
      'Logopädie', 'Ergotherapie', 'Chiropraktiker',
      'Apotheke', 'Pflegedienst', 'Ambulanter Pflegedienst',
      'Tierarzt', 'Tierklinik', 'Optiker',
      'Kardiologe', 'Urologe', 'Frauenarzt',
      'Radiologe', 'Internist', 'Neurologe', 'Kinderarzt',
      'Zahntechnik', 'Dentallabor', 'Sanitätshaus',
    ],
  },
  {
    id: 'recht',
    name: 'Recht & Finanzen',
    keywords: [
      'rechtsanwalt', 'anwalt', 'kanzlei', 'anwaltskanzlei', 'rechtsanwälte',
      'notar', 'notariat',
      'steuerberater', 'steuerbüro', 'steuerberatung', 'buchhalter',
      'wirtschaftsprüfer', 'wirtschaftsprüfung',
      'unternehmensberater', 'unternehmensberatung', 'consulting',
      'finanzberater', 'finanzberatung', 'vermögensberatung',
      'versicherung', 'versicherungsmakler', 'makler',
      'immobilien', 'immobilienmakler', 'hausverwaltung',
      'inkasso', 'schuldnerberatung',
      'patentanwalt', 'patent',
    ],
    scrapeKeywords: [
      'Rechtsanwalt', 'Anwaltskanzlei', 'Notar',
      'Steuerberater', 'Steuerbüro', 'Wirtschaftsprüfer',
      'Unternehmensberatung', 'Finanzberater', 'Vermögensberatung',
      'Versicherungsmakler', 'Versicherungsagentur',
      'Immobilienmakler', 'Hausverwaltung', 'Immobilienverwaltung',
      'Inkasso', 'Schuldnerberatung', 'Patentanwalt',
      'Buchhalter', 'Lohnbüro', 'Wirtschaftsberater',
    ],
  },
  {
    id: 'gastronomie',
    name: 'Gastronomie & Hotellerie',
    keywords: [
      'restaurant', 'gaststätte', 'gasthaus', 'gasthof',
      'café', 'cafe', 'bäckerei', 'konditorei',
      'hotel', 'pension', 'ferienwohnung', 'unterkunft',
      'catering', 'partyservice', 'eventcatering',
      'imbiss', 'döner', 'pizza', 'lieferservice',
      'bar', 'kneipe', 'biergarten', 'lounge',
      'metzger', 'metzgerei', 'fleischerei', 'fleischer',
    ],
    scrapeKeywords: [
      'Restaurant', 'Gaststätte', 'Gasthaus',
      'Café', 'Bäckerei', 'Konditorei',
      'Hotel', 'Pension', 'Ferienwohnung',
      'Catering', 'Partyservice', 'Eventcatering',
      'Imbiss', 'Pizzeria', 'Lieferservice',
      'Metzgerei', 'Fleischerei',
      'Bar', 'Biergarten', 'Weinhandlung',
    ],
  },
  {
    id: 'it',
    name: 'IT & Digital',
    keywords: [
      'webdesign', 'webentwicklung', 'webdesigner', 'webagentur',
      'seo', 'online-marketing', 'onlinemarketing', 'digitalmarketing',
      'it-service', 'it-dienstleister', 'systemhaus', 'edv',
      'softwareentwicklung', 'software', 'app', 'programmierung',
      'werbeagentur', 'agentur', 'kreativagentur', 'marketingagentur',
      'grafikdesign', 'grafik', 'designer', 'design',
      'fotograf', 'fotografie', 'fotostudio',
      'videoproduktion', 'film', 'video', 'kameramann',
      'druck', 'druckerei', 'printmedien', 'werbetechnik',
      'social media', 'socialmedia',
    ],
    scrapeKeywords: [
      'Webdesign Agentur', 'Webagentur', 'Internetagentur',
      'SEO Agentur', 'Online Marketing Agentur',
      'IT Service', 'IT Dienstleister', 'Systemhaus', 'EDV Service',
      'Softwareentwicklung', 'App Entwicklung',
      'Werbeagentur', 'Marketingagentur', 'Kreativagentur',
      'Grafikdesign', 'Grafikdesigner',
      'Fotograf', 'Fotostudio', 'Videoproduktion',
      'Druckerei', 'Werbetechnik', 'Beschriftung',
      'Social Media Agentur', 'Content Marketing',
    ],
  },
  {
    id: 'bildung',
    name: 'Bildung & Coaching',
    keywords: [
      'fahrschule', 'fahrlehrer',
      'nachhilfe', 'lernhilfe', 'tutor',
      'musikschule', 'musik', 'musiklehrer',
      'tanzschule', 'tanz',
      'coaching', 'coach', 'trainer', 'personaltrainer',
      'fitness', 'fitnessstudio', 'gym', 'sport',
      'yoga', 'pilates', 'meditation',
      'sprachschule', 'sprachkurs', 'dolmetscher', 'übersetzer',
      'kindergarten', 'kita', 'kinderbetreuung',
      'hundeschule', 'hundetrainer',
    ],
    scrapeKeywords: [
      'Fahrschule', 'Nachhilfe', 'Musikschule', 'Tanzschule',
      'Coach', 'Business Coaching', 'Personal Trainer',
      'Fitnessstudio', 'Yoga Studio', 'Kampfsportschule',
      'Sprachschule', 'Dolmetscher', 'Übersetzer',
      'Kindergarten', 'Kita', 'Kinderbetreuung',
      'Hundeschule', 'Reitschule', 'Schwimmschule',
    ],
  },
  {
    id: 'beauty',
    name: 'Beauty & Wellness',
    keywords: [
      'friseur', 'frisör', 'haare', 'friseursalon', 'barbershop', 'barber',
      'kosmetik', 'kosmetikstudio', 'beauty', 'schönheitspflege',
      'nagelstudio', 'nägel', 'maniküre', 'nail',
      'tattoo', 'tattoostudio', 'piercing',
      'massage', 'massagepraxis', 'spa', 'wellness', 'sauna',
      'sonnenstudio', 'solarium',
    ],
    scrapeKeywords: [
      'Friseur', 'Friseursalon', 'Barbershop',
      'Kosmetikstudio', 'Beauty Salon',
      'Nagelstudio', 'Tattoo Studio', 'Piercing Studio',
      'Massage', 'Wellness', 'Spa', 'Sauna',
      'Sonnenstudio', 'Permanent Makeup', 'Waxing Studio',
    ],
  },
  {
    id: 'bau',
    name: 'Bau & Architektur',
    keywords: [
      'architekt', 'architektur', 'architekturbüro',
      'bauunternehmen', 'baufirma', 'bauunternehmung', 'hochbau', 'tiefbau',
      'statiker', 'statik', 'ingenieur', 'ingenieurbüro',
      'vermessung', 'vermessungsbüro', 'geodäsie',
      'abbruch', 'abriss', 'entsorgung', 'container',
      'gerüstbau', 'gerüst',
      'pflasterarbeiten', 'pflasterer', 'straßenbau',
      'betonbau', 'beton', 'fertigbau',
      'innenarchitekt', 'innenausbau', 'raumausstatter',
      'küchenstudio', 'küche', 'einbauküche',
    ],
    scrapeKeywords: [
      'Architekturbüro', 'Architekt',
      'Bauunternehmen', 'Baufirma', 'Hochbau', 'Tiefbau',
      'Ingenieurbüro', 'Statiker', 'Tragwerksplanung',
      'Vermessungsbüro', 'Vermessung',
      'Containerservice', 'Entsorgung',
      'Innenarchitekt', 'Innenausbau',
      'Küchenstudio', 'Einbauküchen',
      'Fertighäuser', 'Massivhausbau', 'Holzhausbau',
    ],
  },
  {
    id: 'handel',
    name: 'Handel & Einzelhandel',
    keywords: [
      'blumen', 'blumenladen', 'florist', 'gärtnerei',
      'möbelhaus', 'einrichtung', 'einrichtungshaus',
      'elektromarkt', 'elektronik', 'computer', 'pc',
      'buchhandlung', 'bücher',
      'spielwaren', 'spielzeug',
      'baustoffhandel', 'baustoffe', 'baumarkt',
      'getränkemarkt', 'getränke', 'getränkehandel',
      'autozubehör', 'autoteile', 'reifen', 'reifenhändler',
      'schmuck', 'juwelier', 'goldschmied',
      'textil', 'mode', 'bekleidung', 'boutique',
    ],
    scrapeKeywords: [
      'Blumenladen', 'Florist', 'Gärtnerei',
      'Möbelhaus', 'Einrichtungshaus',
      'Computerladen', 'PC Service',
      'Buchhandlung', 'Spielwarenladen',
      'Baustoffhandel', 'Baustoffe',
      'Getränkemarkt', 'Getränkehandel',
      'Reifenhändler', 'Autoteile',
      'Juwelier', 'Goldschmied', 'Schmuck',
      'Boutique', 'Modegeschäft', 'Textilhandel',
      'Tierhandlung', 'Zoofachhandel',
    ],
  },
];

export function detectCategory(keyword: string): string | null {
  const kw = keyword.toLowerCase().trim();

  for (const cat of CATEGORIES) {
    for (const term of cat.keywords) {
      if (kw.includes(term) || term.includes(kw)) {
        return cat.id;
      }
    }
  }

  return null;
}

export function getCategoryName(categoryId: string): string {
  const cat = CATEGORIES.find(c => c.id === categoryId);
  return cat?.name || categoryId;
}
